# Generated by Django 4.1.3 on 2022-12-04 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='meme',
            field=models.TextField(blank=True, default='https://www.magiquiz.com/wp-content/uploads/2017/10/giphy3.gif', null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='case_check',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='case_explonation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.explonation'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='courses',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courses',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.topic'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='bootcamp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bootcamp'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='explonation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.explonation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
