# Generated by Django 4.1.3 on 2022-12-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classes_gif_alter_bootcamp_case_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamp',
            name='case_check',
        ),
        migrations.RemoveField(
            model_name='bootcamp',
            name='case_explonation',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='bootcamp',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='explonation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Bootcamp',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Explonation',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
